##
## EPITECH PROJECT, 2024
## Zappy
## File description:
## Makefile
##

SRC     =   src/zappy_ai

NAME	=   zappy_ai

all:	$(NAME)

$(NAME):
	cp $(SRC) ../
	chmod +x ../$(NAME)

fclean:
	rm -f ../$(NAME)

re:	fclean all

.PHONY: all fclean re
