#!/usr/bin/env python3
from ZappyAI.src.parseArgs import my_parser
from ZappyAI.src.client.client import Client


def entrypoint() -> int:
    args = my_parser.parser.parse_args(
        None, my_parser.OrderNamespace()
    )
    args.order = args.order[4:]
    if len(args.order) < 3:
        if len(args.order) == 1 and args.order[0][0] == "h":
            print("USAGE: ./zappy_ai -p port -n name -h machine")
            return 0
        return 84

    # if (args.order[0][0] == "h" and ("elp" in args.order[0][1])):
    #     print("USAGE: ./zappy_ai -p port -n name -h machine")
    #     return 0
    try:
        port = int(args.order[0][1][0])
        name = args.order[1][1][0]
        machine = args.order[2][1][0]
    except ValueError:
        return 84
    if (len(args.order) == 4):
        clientId = args.order[3][1][0]
    else:
        clientId = "1"
    print("Client ID: " + clientId)
    client = Client(port, name, machine, clientId)
    client.connectWithServer()
    client.launch_client()
    client.closeConnection()
    return 0


if __name__ == "__main__":
    exit(entrypoint())
